[package]
name = "chapter08"
version = "0.1.0"
edition = "2021"
description = "Common Collections"
# https://doc.rust-lang.org/book/ch08-00-common-collections.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
