[package]
name = "chapter04"
version = "0.1.0"
edition = "2021"
description = "Understanding Ownership"
# https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
