[package]
name = "chapter10"
version = "0.1.0"
edition = "2021"
# https://doc.rust-lang.org/book/ch10-00-generics.html
description = "Generic Types, Traits and Lifetimes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
