[package]
name = "chapter03"
version = "0.1.0"
edition = "2021"
description = "Common Programming Concepts"
# https://doc.rust-lang.org/book/ch03-00-common-programming-concepts.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
