[package]
name = "chapter11"
version = "0.1.0"
edition = "2024"
description = "Writing Automated Tests"
# https://doc.rust-lang.org/book/ch11-00-testing.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
