[package]
name = "chapter16"
version = "0.1.0"
edition = "2024"
description = "Threads, Arc, Mutexes, MPSC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
